{
 "title": "Otus User service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"user-service-deployment.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{namespace=\"default\", pod=~\"user-service-.*\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "User Service API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_count{uri=~\"/user.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 Eternal Server Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method, uri) (rate(http_server_requests_seconds_count{uri=~\"/user.*\", status=\"500\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99,  sum by(le) (rate(http_server_requests_seconds_bucket{uri=~\"/user.*\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(http_server_requests_seconds_max{uri=~\"/user.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}